// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qz8RZNbEpApDh4AbPHEGbs
// Component: iO-P49_GXCxkGL
import * as React from "react"

import { Link, GatsbyLinkProps as LinkProps } from "gatsby"

import * as p from "@plasmicapp/react-web"
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"
import Header from "../../Header" // plasmic-import: p3dZKyTqlfz3uo/component
import Section from "../../Section" // plasmic-import: jD2vOiCCxRDWBU/component
import Bullet from "../../Bullet" // plasmic-import: vNHyFNN70mMBJm/component
import LinkButton from "../../LinkButton" // plasmic-import: xWfXiyMYihr2lP/component
import HomeCta from "../../HomeCta" // plasmic-import: Mnr7gzWjzRaTAZ/component
import Footer from "../../Footer" // plasmic-import: _eGqY2jCOfhYgO/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen" // plasmic-import: cUnl2He_iVdlaC/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_simple_light_landing_page.module.css" // plasmic-import: qz8RZNbEpApDh4AbPHEGbs/projectcss
import * as sty from "./PlasmicFeatures.module.css" // plasmic-import: iO-P49_GXCxkGL/css

import simpleProjectQp7GFdXKzdoQl from "./images/simpleProject.png" // plasmic-import: qp7gFd-xKZDOQl/picture
import taskLYGpxyTfRh8Mi2 from "./images/task.png" // plasmic-import: lYGpxyTfRh8mi2/picture

export type PlasmicFeatures__VariantMembers = {}

export type PlasmicFeatures__VariantsArgs = {}
type VariantPropType = keyof PlasmicFeatures__VariantsArgs
export const PlasmicFeatures__VariantProps = new Array<VariantPropType>()

export type PlasmicFeatures__ArgsType = {}
type ArgPropType = keyof PlasmicFeatures__ArgsType
export const PlasmicFeatures__ArgProps = new Array<ArgPropType>()

export type PlasmicFeatures__OverridesType = {
  root?: p.Flex<"div">
  header?: p.Flex<typeof Header>
  section?: p.Flex<typeof Section>
  homeCta?: p.Flex<typeof HomeCta>
  footer?: p.Flex<typeof Footer>
}

export interface DefaultFeaturesProps {
  className?: string
}

function PlasmicFeatures__RenderFunc(props: {
  variants: PlasmicFeatures__VariantsArgs
  args: PlasmicFeatures__ArgsType
  overrides: PlasmicFeatures__OverridesType
  dataFetches?: PlasmicFeatures__Fetches
  forNode?: string
}) {
  const { variants, args, overrides, forNode, dataFetches } = props

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants(),
  })

  return (
    <React.Fragment>
      {}

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.box__fZc5K)}
          >
            <Header
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames("__wab_instance", sty.header)}
            />

            <Section
              data-plasmic-name={"section"}
              data-plasmic-override={overrides.section}
              className={classNames("__wab_instance", sty.section)}
              subtitle={
                "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur excepteur sint occaecat cupidatat."
              }
              title={"The ultimate in feature set."}
            />

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__mkmB)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__jPqCx)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__mJLjQ
                  )}
                >
                  {"Powerful suite of tools"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box___8QVjb
                  )}
                >
                  {
                    "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore pariatur."
                  }
                </div>

                <Bullet
                  className={classNames("__wab_instance", sty.bullet__xs0KQ)}
                />

                <Bullet
                  className={classNames("__wab_instance", sty.bullet__qe0Gu)}
                />

                <Bullet
                  className={classNames("__wab_instance", sty.bullet__g6Wx)}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__kEQw
                  )}
                >
                  {
                    "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore pariatur."
                  }
                </div>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__d6Y51)}
                >
                  <LinkButton
                    text={"Start free trial"}
                    type={"solidBlue" as const}
                  />

                  <LinkButton
                    text={"View demo"}
                    type={"outlineBlue" as const}
                  />
                </p.Stack>
              </p.Stack>

              <div className={classNames(defaultcss.all, sty.box__znAyv)}>
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__mBrGz)}
                  role={"img"}
                  src={simpleProjectQp7GFdXKzdoQl}
                />

                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__ub3Hw)}
                  role={"img"}
                  src={taskLYGpxyTfRh8Mi2}
                />
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__ldM5V)}
            >
              <div className={classNames(defaultcss.all, sty.box__bJfQi)}>
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img___1Bw2)}
                  role={"img"}
                  src={simpleProjectQp7GFdXKzdoQl}
                />

                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__vToCo)}
                  role={"img"}
                  src={taskLYGpxyTfRh8Mi2}
                />
              </div>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__gZqp4)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box___1L6Zp
                  )}
                >
                  {"Powerful suite of tools"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__fpKbC
                  )}
                >
                  {
                    "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore pariatur."
                  }
                </div>

                <Bullet
                  className={classNames("__wab_instance", sty.bullet__xiSxF)}
                />

                <Bullet
                  className={classNames("__wab_instance", sty.bullet__zb6Oj)}
                />

                <Bullet
                  className={classNames("__wab_instance", sty.bullet__rola9)}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__hgdFu
                  )}
                >
                  {
                    "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore pariatur."
                  }
                </div>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__zVYj)}
                >
                  <LinkButton
                    text={"Start free trial"}
                    type={"solidBlue" as const}
                  />

                  <LinkButton
                    text={"View demo"}
                    type={"outlineBlue" as const}
                  />
                </p.Stack>
              </p.Stack>
            </p.Stack>

            <HomeCta
              data-plasmic-name={"homeCta"}
              data-plasmic-override={overrides.homeCta}
              className={classNames("__wab_instance", sty.homeCta)}
            />

            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </p.Stack>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null
}

const PlasmicDescendants = {
  root: ["root", "header", "section", "homeCta", "footer"],
  header: ["header"],
  section: ["section"],
  homeCta: ["homeCta"],
  footer: ["footer"],
} as const
type NodeNameType = keyof typeof PlasmicDescendants
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number]
type NodeDefaultElementType = {
  root: "div"
  header: typeof Header
  section: typeof Section
  homeCta: typeof HomeCta
  footer: typeof Footer
}

type ReservedPropsType = "variants" | "args" | "overrides"
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFeatures__OverridesType,
  DescendantsType<T>
>
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicFeatures__VariantsArgs
  args?: PlasmicFeatures__ArgsType
  overrides?: NodeOverridesType<T>
  dataFetches?: PlasmicFeatures__Fetches
} & Omit<PlasmicFeatures__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicFeatures__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key }
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFeatures__ArgProps,
      internalVariantPropNames: PlasmicFeatures__VariantProps,
    })

    const { dataFetches } = props

    return PlasmicFeatures__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicFeatures"
  } else {
    func.displayName = `PlasmicFeatures.${nodeName}`
  }
  return func
}

export const PlasmicFeatures = Object.assign(
  // Top-level PlasmicFeatures renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    section: makeNodeComponent("section"),
    homeCta: makeNodeComponent("homeCta"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicFeatures
    internalVariantProps: PlasmicFeatures__VariantProps,
    internalArgProps: PlasmicFeatures__ArgProps,
  }
)

export default PlasmicFeatures
/* prettier-ignore-end */
